import re

with open('wehouse-gsap-script.js', 'r', encoding='utf-8', errors='ignore') as f:
    gsap_script = f.read()

# Simple replacements for GSAP script
replacements = {
    'bg-amber-50': 'bg-primary-lighter',
    'bg-amber-100': 'bg-primary-lighter',
    'bg-amber-200': 'bg-primary-light',
    'bg-amber-300': 'bg-primary-light',
    'bg-amber-400': 'bg-primary-light',
    'bg-amber-500': 'bg-primary',
    'bg-amber-600': 'bg-primary-hover',
    'bg-orange-50': 'bg-primary-lighter',
    'bg-orange-100': 'bg-primary-lighter',
    'bg-orange-200': 'bg-primary-light',
    'bg-orange-300': 'bg-primary-light',
    'bg-orange-400': 'bg-primary-light',
    'bg-orange-500': 'bg-primary',
    'bg-orange-600': 'bg-primary-hover',
    'text-amber-400': 'text-primary-light',
    'text-amber-500': 'text-primary',
    'text-amber-600': 'text-primary',
    'text-amber-700': 'text-primary-hover',
    'text-amber-800': 'text-primary-hover',
    'text-amber-900': 'text-primary-hover',
    'text-orange-400': 'text-primary-light',
    'text-orange-500': 'text-primary',
    'text-orange-600': 'text-primary',
    'text-orange-700': 'text-primary-hover',
    'text-orange-800': 'text-primary-hover',
    'border-amber-200': 'border-primary-light',
    'border-amber-300': 'border-primary-light',
    'border-amber-400': 'border-primary-light',
    'border-amber-500': 'border-primary',
    'border-amber-500/30': 'border-primary/30',
    'border-amber-500/45': 'border-primary/45',
    'border-amber-500/55': 'border-primary/55',
    'border-amber-500/12': 'border-primary/12',
    'border-amber-200/80': 'border-primary-light/80',
    'border-amber-200/90': 'border-primary-light/90',
    'border-amber-500/35': 'border-primary/35',
    'border-amber-500/10': 'border-primary/10',
    'border-orange-200': 'border-primary-light',
    'border-orange-500': 'border-primary',
    'border-orange-500/35': 'border-primary/35',
    'border-orange-600': 'border-primary-hover',
    'hover:bg-amber-50': 'hover:bg-primary-lighter',
    'hover:bg-amber-50/55': 'hover:bg-primary-lighter/55',
    'hover:bg-amber-50/35': 'hover:bg-primary-lighter/35',
    'hover:bg-orange-50': 'hover:bg-primary-lighter',
    'hover:bg-orange-50/35': 'hover:bg-primary-lighter/35',
    'hover:bg-orange-100': 'hover:bg-primary-lighter',
    'hover:bg-orange-500': 'hover:bg-primary',
    'hover:bg-orange-600': 'hover:bg-primary-hover',
    'hover:bg-orange-700': 'hover:bg-primary-hover',
    'hover:border-amber-500': 'hover:border-primary',
    'hover:border-amber-300': 'hover:border-primary-light',
    'hover:border-orange-500': 'hover:border-primary',
    'hover:border-orange-500/55': 'hover:border-primary/55',
    'hover:text-amber-500': 'hover:text-primary',
    'hover:text-amber-600': 'hover:text-primary',
    'hover:text-amber-700': 'hover:text-primary-hover',
    'hover:text-orange-500': 'hover:text-primary',
    'hover:text-orange-600': 'hover:text-primary',
    'hover:text-orange-700': 'hover:text-primary-hover',
    'hover:text-amber-400': 'hover:text-primary-light',
    'group-hover:bg-amber-600': 'group-hover:bg-primary-hover',
    'group-hover:bg-orange-600': 'group-hover:bg-primary-hover',
    'focus-visible:outline-amber-500': 'focus-visible:outline-primary',
    'ring-amber-300': 'ring-primary-light',
    'ring-amber-500': 'ring-primary',
    'ring-amber-300/60': 'ring-primary-light/60',
    'shadow-amber-200/60': 'shadow-primary/20',
    'shadow-amber-500/7': 'shadow-primary/7',
    'shadow-amber-400/25': 'shadow-primary-light/25',
    'shadow-orange-400/25': 'shadow-primary-light/25',
    'shadow-orange-500/16': 'shadow-primary/16',
    'from-amber-50': 'from-primary-lighter',
    'to-orange-50': 'to-primary-lighter',
    'from-amber-100': 'from-primary-lighter',
    'to-amber-50': 'to-primary-lighter',
    'from-amber-500': 'from-primary',
    'via-amber-500': 'via-primary',
    'to-amber-500': 'to-primary',
    'from-orange-600': 'from-primary-hover',
    'via-orange-500': 'via-primary',
    'to-orange-400': 'to-primary-light',
    'from-orange-500': 'from-primary',
    'to-orange-500': 'to-primary',
    'from-orange-50': 'from-primary-lighter',
    'to-orange-50': 'to-primary-lighter',
    'from-amber-200': 'from-primary-light',
    'to-amber-100': 'to-primary-lighter',
    'from-orange-400': 'from-primary-light',
    'to-orange-500': 'to-primary',
    'from-orange-500': 'from-primary',
    'to-orange-600': 'to-primary-hover',
    'text-amber-600': 'text-primary',
    'text-amber-500/80': 'text-primary/80',
    'text-amber-900/80': 'text-primary-hover/80',
    'text-orange-800': 'text-primary-hover',
    'text-orange-700': 'text-primary-hover',
    'bg-gradient-to-br from-amber-50 to-white': 'bg-gradient-to-br from-primary-lighter to-white',
    'bg-gradient-to-br from-amber-50 to-amber-50/15': 'bg-gradient-to-br from-primary-lighter to-primary-lighter/15',
    'bg-gradient-to-br from-white to-amber-50': 'bg-gradient-to-br from-white to-primary-lighter',
    'bg-gradient-to-br from-amber-50 to-amber-50': 'bg-gradient-to-br from-primary-lighter to-primary-lighter',
    'bg-gradient-to-br from-orange-600 via-orange-500 to-orange-400': 'bg-gradient-to-br from-primary-hover via-primary to-primary-light',
    'bg-gradient-to-br from-gray-700 to-gray-900': 'bg-gradient-to-br from-gray-700 to-gray-900',
    'bg-gradient-to-br from-orange-600 to-orange-500': 'bg-gradient-to-br from-primary-hover to-primary',
    'bg-gradient-to-br from-amber-600 to-amber-500': 'bg-gradient-to-br from-primary-hover to-primary',
    'bg-gradient-to-br from-amber-500 to-amber-500': 'bg-gradient-to-br from-primary to-primary',
    'bg-gradient-to-br from-amber-50 to-amber-50/15': 'bg-gradient-to-br from-primary-lighter to-primary-lighter/15',
    'var(--color-amber-300)': 'var(--color-primary-light)',
    'var(--color-amber-200)': 'var(--color-primary-lighter)',
    'var(--color-orange-200)': 'var(--color-primary-lighter)',
    'var(--color-orange-300)': 'var(--color-primary-light)',
    'var(--color-orange-400)': 'var(--color-primary-light)',
    'var(--color-amber-400)': 'var(--color-primary-light)',
    'var(--color-amber-500)': 'var(--color-primary)',
    'var(--color-amber-600)': 'var(--color-primary-hover)',
    'var(--color-amber-700)': 'var(--color-primary-hover)',
    'var(--color-amber-800)': 'var(--color-primary-hover)',
    'var(--color-orange-500)': 'var(--color-primary)',
    'var(--color-orange-600)': 'var(--color-primary-hover)',
    'var(--color-orange-700)': 'var(--color-primary-hover)',
    'var(--color-orange-800)': 'var(--color-primary-hover)',
}

for old, new in replacements.items():
    gsap_script = gsap_script.replace(old, new)

gsap_script = gsap_script.replace('WeHouse', 'MAKAAN WALEY')
gsap_script = gsap_script.replace('wehouse', 'makaan-waley')
gsap_script = gsap_script.replace('WEHOUSE', 'MAKAAN WALEY')
gsap_script = gsap_script.replace('Wehouse', 'Makaan Waley')

with open('gsap-script-modified.js', 'w', encoding='utf-8') as f:
    f.write(gsap_script)

print('GSAP script modified and saved')